#############################################################################
# Makefile for building: qModMaster
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ../QModMaster/qModMaster.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ../QModMaster/qModMaster.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_TTY_POSIX_ -DQS_LOG_LINE_NUMBERS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++11 -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../QModMaster -I. -I../QModMaster/3rdparty/libmodbus -I../QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qModMaster1.0.0
DISTDIR = /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/.tmp/qModMaster1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../QModMaster/src/main.cpp \
		../QModMaster/src/mainwindow.cpp \
		../QModMaster/3rdparty/libmodbus/modbus.c \
		../QModMaster/forms/about.cpp \
		../QModMaster/forms/settingsmodbusrtu.cpp \
		../QModMaster/forms/settingsmodbustcp.cpp \
		../QModMaster/src/modbusadapter.cpp \
		../QModMaster/src/eutils.cpp \
		../QModMaster/src/registersmodel.cpp \
		../QModMaster/src/rawdatamodel.cpp \
		../QModMaster/forms/settings.cpp \
		../QModMaster/forms/busmonitor.cpp \
		../QModMaster/3rdparty/libmodbus/modbus-data.c \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.c \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.c \
		../QModMaster/src/rawdatadelegate.cpp \
		../QModMaster/src/registersdatadelegate.cpp \
		../QModMaster/src/modbuscommsettings.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDest.cpp \
		../QModMaster/3rdparty/QsLog/QsLog.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDestConsole.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDestFile.cpp \
		../QModMaster/src/infobar.cpp \
		../QModMaster/forms/tools.cpp qrc_icons.cpp \
		qrc_translations.cpp \
		moc_mainwindow.cpp \
		moc_about.cpp \
		moc_settingsmodbusrtu.cpp \
		moc_settingsmodbustcp.cpp \
		moc_modbusadapter.cpp \
		moc_registersmodel.cpp \
		moc_rawdatamodel.cpp \
		moc_settings.cpp \
		moc_busmonitor.cpp \
		moc_rawdatadelegate.cpp \
		moc_registersdatadelegate.cpp \
		moc_modbuscommsettings.cpp \
		moc_infobar.cpp \
		moc_tools.cpp
OBJECTS       = main.o \
		mainwindow.o \
		modbus.o \
		about.o \
		settingsmodbusrtu.o \
		settingsmodbustcp.o \
		modbusadapter.o \
		eutils.o \
		registersmodel.o \
		rawdatamodel.o \
		settings.o \
		busmonitor.o \
		modbus-data.o \
		modbus-tcp.o \
		modbus-rtu.o \
		rawdatadelegate.o \
		registersdatadelegate.o \
		modbuscommsettings.o \
		QsLogDest.o \
		QsLog.o \
		QsLogDestConsole.o \
		QsLogDestFile.o \
		infobar.o \
		tools.o \
		qrc_icons.o \
		qrc_translations.o \
		moc_mainwindow.o \
		moc_about.o \
		moc_settingsmodbusrtu.o \
		moc_settingsmodbustcp.o \
		moc_modbusadapter.o \
		moc_registersmodel.o \
		moc_rawdatamodel.o \
		moc_settings.o \
		moc_busmonitor.o \
		moc_rawdatadelegate.o \
		moc_registersdatadelegate.o \
		moc_modbuscommsettings.o \
		moc_infobar.o \
		moc_tools.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../QModMaster/qModMaster.pro ../QModMaster/src/mainwindow.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatadelegate.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDestConsole.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h \
		../QModMaster/3rdparty/QsLog/QsLogDestFile.h \
		../QModMaster/src/infobar.h \
		../QModMaster/forms/tools.h ../QModMaster/src/main.cpp \
		../QModMaster/src/mainwindow.cpp \
		../QModMaster/3rdparty/libmodbus/modbus.c \
		../QModMaster/forms/about.cpp \
		../QModMaster/forms/settingsmodbusrtu.cpp \
		../QModMaster/forms/settingsmodbustcp.cpp \
		../QModMaster/src/modbusadapter.cpp \
		../QModMaster/src/eutils.cpp \
		../QModMaster/src/registersmodel.cpp \
		../QModMaster/src/rawdatamodel.cpp \
		../QModMaster/forms/settings.cpp \
		../QModMaster/forms/busmonitor.cpp \
		../QModMaster/3rdparty/libmodbus/modbus-data.c \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.c \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.c \
		../QModMaster/src/rawdatadelegate.cpp \
		../QModMaster/src/registersdatadelegate.cpp \
		../QModMaster/src/modbuscommsettings.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDest.cpp \
		../QModMaster/3rdparty/QsLog/QsLog.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDestConsole.cpp \
		../QModMaster/3rdparty/QsLog/QsLogDestFile.cpp \
		../QModMaster/src/infobar.cpp \
		../QModMaster/forms/tools.cpp
QMAKE_TARGET  = qModMaster
DESTDIR       = 
TARGET        = qModMaster


first: all
####### Build rules

qModMaster: ui_mainwindow.h ui_about.h ui_settingsmodbusrtu.h ui_settingsmodbustcp.h ui_settings.h ui_busmonitor.h ui_tools.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../QModMaster/qModMaster.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../QModMaster/qModMaster.pro \
		../QModMaster/icons/icons.qrc \
		../QModMaster/translations/translations.qrc
	$(QMAKE) -o Makefile ../QModMaster/qModMaster.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
../QModMaster/qModMaster.pro:
../QModMaster/icons/icons.qrc:
../QModMaster/translations/translations.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ../QModMaster/qModMaster.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile qModMaster

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../QModMaster/icons/icons.qrc ../QModMaster/translations/translations.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../QModMaster/src/mainwindow.h ../QModMaster/3rdparty/libmodbus/modbus.h ../QModMaster/forms/about.h ../QModMaster/forms/settingsmodbusrtu.h ../QModMaster/forms/settingsmodbustcp.h ../QModMaster/src/modbusadapter.h ../QModMaster/src/eutils.h ../QModMaster/src/registersmodel.h ../QModMaster/src/rawdatamodel.h ../QModMaster/forms/settings.h ../QModMaster/forms/busmonitor.h ../QModMaster/src/rawdatadelegate.h ../QModMaster/src/registersdatadelegate.h ../QModMaster/src/modbuscommsettings.h ../QModMaster/3rdparty/QsLog/QsLog.h ../QModMaster/3rdparty/QsLog/QsLogDest.h ../QModMaster/3rdparty/QsLog/QsLogDestConsole.h ../QModMaster/3rdparty/QsLog/QsLogLevel.h ../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h ../QModMaster/3rdparty/QsLog/QsLogDestFile.h ../QModMaster/src/infobar.h ../QModMaster/forms/tools.h $(DISTDIR)/
	$(COPY_FILE) --parents ../QModMaster/src/main.cpp ../QModMaster/src/mainwindow.cpp ../QModMaster/3rdparty/libmodbus/modbus.c ../QModMaster/forms/about.cpp ../QModMaster/forms/settingsmodbusrtu.cpp ../QModMaster/forms/settingsmodbustcp.cpp ../QModMaster/src/modbusadapter.cpp ../QModMaster/src/eutils.cpp ../QModMaster/src/registersmodel.cpp ../QModMaster/src/rawdatamodel.cpp ../QModMaster/forms/settings.cpp ../QModMaster/forms/busmonitor.cpp ../QModMaster/3rdparty/libmodbus/modbus-data.c ../QModMaster/3rdparty/libmodbus/modbus-tcp.c ../QModMaster/3rdparty/libmodbus/modbus-rtu.c ../QModMaster/src/rawdatadelegate.cpp ../QModMaster/src/registersdatadelegate.cpp ../QModMaster/src/modbuscommsettings.cpp ../QModMaster/3rdparty/QsLog/QsLogDest.cpp ../QModMaster/3rdparty/QsLog/QsLog.cpp ../QModMaster/3rdparty/QsLog/QsLogDestConsole.cpp ../QModMaster/3rdparty/QsLog/QsLogDestFile.cpp ../QModMaster/src/infobar.cpp ../QModMaster/forms/tools.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../QModMaster/forms/mainwindow.ui ../QModMaster/forms/about.ui ../QModMaster/forms/settingsmodbusrtu.ui ../QModMaster/forms/settingsmodbustcp.ui ../QModMaster/forms/settings.ui ../QModMaster/forms/busmonitor.ui ../QModMaster/forms/tools.ui $(DISTDIR)/
	$(COPY_FILE) --parents translations/qModMaster_zh_CN.ts translations/qModMaster_zh_TW.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp qrc_translations.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_translations.cpp
qrc_icons.cpp: ../QModMaster/icons/icons.qrc \
		/usr/lib/qt5/bin/rcc \
		../QModMaster/icons/TV-16.png \
		../QModMaster/icons/document-export-16.png \
		../QModMaster/icons/Header16.png \
		../QModMaster/icons/cyclic-process-16.png \
		../QModMaster/icons/text-x-log-16.png \
		../QModMaster/icons/close8-black.png \
		../QModMaster/icons/close8-red.png \
		../QModMaster/icons/data-sort-16.png \
		../QModMaster/icons/connect-24.png \
		../QModMaster/icons/reset-16.png \
		../QModMaster/icons/ethernet-port-16.png \
		../QModMaster/icons/usa-flag-16.png \
		../QModMaster/icons/save-16.png \
		../QModMaster/icons/plug-connect-16.png \
		../QModMaster/icons/China-flag-16.png \
		../QModMaster/icons/exit-16.png \
		../QModMaster/icons/info-sign-16.png \
		../QModMaster/icons/tools-16.png \
		../QModMaster/icons/edit-16.png \
		../QModMaster/icons/options-16.png \
		../QModMaster/icons/play-16.png \
		../QModMaster/icons/bullet-green-16.png \
		../QModMaster/icons/document-import-16.png \
		../QModMaster/icons/edit-clear-16.png \
		../QModMaster/icons/bullet-red-16.png \
		../QModMaster/icons/Taiwan-flag-16.png \
		../QModMaster/icons/Close-16.png \
		../QModMaster/icons/help-desk-icon-16.png \
		../QModMaster/icons/plug-disconnect-16.png \
		../QModMaster/icons/serial-pot-16.png
	/usr/lib/qt5/bin/rcc -name icons ../QModMaster/icons/icons.qrc -o qrc_icons.cpp

qrc_translations.cpp: ../QModMaster/translations/translations.qrc \
		/usr/lib/qt5/bin/rcc \
		../QModMaster/translations/qModMaster_zh_TW.qm \
		../QModMaster/translations/qModMaster_zh_CN.qm
	/usr/lib/qt5/bin/rcc -name translations ../QModMaster/translations/translations.qrc -o qrc_translations.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=gnu++11 -g -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_about.cpp moc_settingsmodbusrtu.cpp moc_settingsmodbustcp.cpp moc_modbusadapter.cpp moc_registersmodel.cpp moc_rawdatamodel.cpp moc_settings.cpp moc_busmonitor.cpp moc_rawdatadelegate.cpp moc_registersdatadelegate.cpp moc_modbuscommsettings.cpp moc_infobar.cpp moc_tools.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_about.cpp moc_settingsmodbusrtu.cpp moc_settingsmodbustcp.cpp moc_modbusadapter.cpp moc_registersmodel.cpp moc_rawdatamodel.cpp moc_settings.cpp moc_busmonitor.cpp moc_rawdatadelegate.cpp moc_registersdatadelegate.cpp moc_modbuscommsettings.cpp moc_infobar.cpp moc_tools.cpp
moc_mainwindow.cpp: ../QModMaster/src/mainwindow.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/infobar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/mainwindow.h -o moc_mainwindow.cpp

moc_about.cpp: ../QModMaster/forms/about.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/about.h -o moc_about.cpp

moc_settingsmodbusrtu.cpp: ../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/settingsmodbusrtu.h -o moc_settingsmodbusrtu.cpp

moc_settingsmodbustcp.cpp: ../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/src/modbuscommsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/settingsmodbustcp.h -o moc_settingsmodbustcp.cpp

moc_modbusadapter.cpp: ../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/src/eutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/modbusadapter.h -o moc_modbusadapter.cpp

moc_registersmodel.cpp: ../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/registersmodel.h -o moc_registersmodel.cpp

moc_rawdatamodel.cpp: ../QModMaster/src/rawdatamodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/rawdatamodel.h -o moc_rawdatamodel.cpp

moc_settings.cpp: ../QModMaster/forms/settings.h \
		../QModMaster/src/modbuscommsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/settings.h -o moc_settings.cpp

moc_busmonitor.cpp: ../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/busmonitor.h -o moc_busmonitor.cpp

moc_rawdatadelegate.cpp: ../QModMaster/src/rawdatadelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/rawdatadelegate.h -o moc_rawdatadelegate.cpp

moc_registersdatadelegate.cpp: ../QModMaster/src/registersdatadelegate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/registersdatadelegate.h -o moc_registersdatadelegate.cpp

moc_modbuscommsettings.cpp: ../QModMaster/src/modbuscommsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/modbuscommsettings.h -o moc_modbuscommsettings.cpp

moc_infobar.cpp: ../QModMaster/src/infobar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/src/infobar.h -o moc_infobar.cpp

moc_tools.cpp: ../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/modbuscommsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/mikhail/Разработка/6_sem/ОтЖеки/build-qModMaster-Desktop-Debug/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/libmodbus -I/home/mikhail/Разработка/6_sem/ОтЖеки/QModMaster/3rdparty/QsLog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../QModMaster/forms/tools.h -o moc_tools.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_about.h ui_settingsmodbusrtu.h ui_settingsmodbustcp.h ui_settings.h ui_busmonitor.h ui_tools.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_about.h ui_settingsmodbusrtu.h ui_settingsmodbustcp.h ui_settings.h ui_busmonitor.h ui_tools.h
ui_mainwindow.h: ../QModMaster/forms/mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		../QModMaster/src/infobar.h
	/usr/lib/qt5/bin/uic ../QModMaster/forms/mainwindow.ui -o ui_mainwindow.h

ui_about.h: ../QModMaster/forms/about.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/about.ui -o ui_about.h

ui_settingsmodbusrtu.h: ../QModMaster/forms/settingsmodbusrtu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/settingsmodbusrtu.ui -o ui_settingsmodbusrtu.h

ui_settingsmodbustcp.h: ../QModMaster/forms/settingsmodbustcp.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/settingsmodbustcp.ui -o ui_settingsmodbustcp.h

ui_settings.h: ../QModMaster/forms/settings.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/settings.ui -o ui_settings.h

ui_busmonitor.h: ../QModMaster/forms/busmonitor.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/busmonitor.ui -o ui_busmonitor.h

ui_tools.h: ../QModMaster/forms/tools.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../QModMaster/forms/tools.ui -o ui_tools.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../QModMaster/src/main.cpp ../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h \
		../QModMaster/src/mainwindow.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/infobar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../QModMaster/src/main.cpp

mainwindow.o: ../QModMaster/src/mainwindow.cpp ../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h \
		../QModMaster/src/mainwindow.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/infobar.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../QModMaster/src/mainwindow.cpp

modbus.o: ../QModMaster/3rdparty/libmodbus/modbus.c ../QModMaster/3rdparty/libmodbus/config.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/3rdparty/libmodbus/modbus-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus.o ../QModMaster/3rdparty/libmodbus/modbus.c

about.o: ../QModMaster/forms/about.cpp ../QModMaster/forms/about.h \
		ui_about.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o ../QModMaster/forms/about.cpp

settingsmodbusrtu.o: ../QModMaster/forms/settingsmodbusrtu.cpp ../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		ui_settingsmodbusrtu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsmodbusrtu.o ../QModMaster/forms/settingsmodbusrtu.cpp

settingsmodbustcp.o: ../QModMaster/forms/settingsmodbustcp.cpp ../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/src/modbuscommsettings.h \
		ui_settingsmodbustcp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsmodbustcp.o ../QModMaster/forms/settingsmodbustcp.cpp

modbusadapter.o: ../QModMaster/src/modbusadapter.cpp ../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/mainwindow.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/forms/tools.h \
		../QModMaster/src/infobar.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusadapter.o ../QModMaster/src/modbusadapter.cpp

eutils.o: ../QModMaster/src/eutils.cpp ../QModMaster/src/eutils.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eutils.o ../QModMaster/src/eutils.cpp

registersmodel.o: ../QModMaster/src/registersmodel.cpp ../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h \
		../QModMaster/src/eutils.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registersmodel.o ../QModMaster/src/registersmodel.cpp

rawdatamodel.o: ../QModMaster/src/rawdatamodel.cpp ../QModMaster/src/rawdatamodel.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawdatamodel.o ../QModMaster/src/rawdatamodel.cpp

settings.o: ../QModMaster/forms/settings.cpp ../QModMaster/forms/settings.h \
		../QModMaster/src/modbuscommsettings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o ../QModMaster/forms/settings.cpp

busmonitor.o: ../QModMaster/forms/busmonitor.cpp ../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		ui_busmonitor.h \
		../QModMaster/src/rawdatadelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o busmonitor.o ../QModMaster/forms/busmonitor.cpp

modbus-data.o: ../QModMaster/3rdparty/libmodbus/modbus-data.c ../QModMaster/3rdparty/libmodbus/config.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-data.o ../QModMaster/3rdparty/libmodbus/modbus-data.c

modbus-tcp.o: ../QModMaster/3rdparty/libmodbus/modbus-tcp.c ../QModMaster/3rdparty/libmodbus/modbus-private.h \
		../QModMaster/3rdparty/libmodbus/config.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-tcp.o ../QModMaster/3rdparty/libmodbus/modbus-tcp.c

modbus-rtu.o: ../QModMaster/3rdparty/libmodbus/modbus-rtu.c ../QModMaster/3rdparty/libmodbus/modbus-private.h \
		../QModMaster/3rdparty/libmodbus/config.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-rtu.o ../QModMaster/3rdparty/libmodbus/modbus-rtu.c

rawdatadelegate.o: ../QModMaster/src/rawdatadelegate.cpp ../QModMaster/src/rawdatadelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawdatadelegate.o ../QModMaster/src/rawdatadelegate.cpp

registersdatadelegate.o: ../QModMaster/src/registersdatadelegate.cpp ../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/mainwindow.h \
		../QModMaster/forms/about.h \
		../QModMaster/forms/settingsmodbusrtu.h \
		../QModMaster/src/modbuscommsettings.h \
		../QModMaster/forms/settingsmodbustcp.h \
		../QModMaster/forms/settings.h \
		../QModMaster/forms/busmonitor.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/infobar.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registersdatadelegate.o ../QModMaster/src/registersdatadelegate.cpp

modbuscommsettings.o: ../QModMaster/src/modbuscommsettings.cpp ../QModMaster/src/modbuscommsettings.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbuscommsettings.o ../QModMaster/src/modbuscommsettings.cpp

QsLogDest.o: ../QModMaster/3rdparty/QsLog/QsLogDest.cpp ../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDestConsole.h \
		../QModMaster/3rdparty/QsLog/QsLogDestFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLogDest.o ../QModMaster/3rdparty/QsLog/QsLogDest.cpp

QsLog.o: ../QModMaster/3rdparty/QsLog/QsLog.cpp ../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLog.o ../QModMaster/3rdparty/QsLog/QsLog.cpp

QsLogDestConsole.o: ../QModMaster/3rdparty/QsLog/QsLogDestConsole.cpp ../QModMaster/3rdparty/QsLog/QsLogDestConsole.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLogDestConsole.o ../QModMaster/3rdparty/QsLog/QsLogDestConsole.cpp

QsLogDestFile.o: ../QModMaster/3rdparty/QsLog/QsLogDestFile.cpp ../QModMaster/3rdparty/QsLog/QsLogDestFile.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLogDestFile.o ../QModMaster/3rdparty/QsLog/QsLogDestFile.cpp

infobar.o: ../QModMaster/src/infobar.cpp ../QModMaster/src/infobar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infobar.o ../QModMaster/src/infobar.cpp

tools.o: ../QModMaster/forms/tools.cpp ../QModMaster/forms/tools.h \
		../QModMaster/src/modbusadapter.h \
		../QModMaster/3rdparty/libmodbus/modbus.h \
		../QModMaster/3rdparty/libmodbus/modbus-version.h \
		../QModMaster/3rdparty/libmodbus/modbus-tcp.h \
		../QModMaster/3rdparty/libmodbus/modbus-rtu.h \
		../QModMaster/src/registersmodel.h \
		../QModMaster/src/registersdatadelegate.h \
		../QModMaster/src/rawdatamodel.h \
		../QModMaster/src/eutils.h \
		../QModMaster/src/modbuscommsettings.h \
		ui_tools.h \
		../QModMaster/3rdparty/QsLog/QsLog.h \
		../QModMaster/3rdparty/QsLog/QsLogLevel.h \
		../QModMaster/3rdparty/QsLog/QsLogDest.h \
		../QModMaster/3rdparty/QsLog/QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o ../QModMaster/forms/tools.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_translations.o: qrc_translations.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_translations.o qrc_translations.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_settingsmodbusrtu.o: moc_settingsmodbusrtu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsmodbusrtu.o moc_settingsmodbusrtu.cpp

moc_settingsmodbustcp.o: moc_settingsmodbustcp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsmodbustcp.o moc_settingsmodbustcp.cpp

moc_modbusadapter.o: moc_modbusadapter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbusadapter.o moc_modbusadapter.cpp

moc_registersmodel.o: moc_registersmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registersmodel.o moc_registersmodel.cpp

moc_rawdatamodel.o: moc_rawdatamodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rawdatamodel.o moc_rawdatamodel.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_busmonitor.o: moc_busmonitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_busmonitor.o moc_busmonitor.cpp

moc_rawdatadelegate.o: moc_rawdatadelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rawdatadelegate.o moc_rawdatadelegate.cpp

moc_registersdatadelegate.o: moc_registersdatadelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registersdatadelegate.o moc_registersdatadelegate.cpp

moc_modbuscommsettings.o: moc_modbuscommsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbuscommsettings.o moc_modbuscommsettings.cpp

moc_infobar.o: moc_infobar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infobar.o moc_infobar.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

